function createfigure(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 30-Jan-2022 20:07:01

% Create figure
figure('OuterPosition',[481 325.4 574.4 509.6]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','q_z');

% Create plot
plot(X2,Y2,'DisplayName','q');

% Create plot
plot(X3,Y3,'DisplayName','(0.6, 0.7) [m]','Marker','x','LineStyle','none');

% Create ylabel
ylabel('y [m]');

% Create xlabel
xlabel('x [m]');

% Create title
title({'trajektoria ruchu','robota na p≥aszczyünie'});

box(axes1,'on');
grid(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.649880980275926 0.44269839795052 0.213928574357714 0.13761905061631]);

